steps:
  # ---------------------------------------------------------------------------
  # 🐍 BACKEND (Python FastAPI on Cloud Run)
  # ---------------------------------------------------------------------------
  
  # 1. Build Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/metodo-activa-brain/server:latest', 'apps/api']

  # 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/metodo-activa-brain/server:latest']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'metodo-activa-brain'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/metodo-activa-brain/server:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,VERTEX_REGION=us-central1,Environment=Production'

  # ---------------------------------------------------------------------------
  # ⚛️ FRONTEND (React + Vite to Firebase Hosting)
  # ---------------------------------------------------------------------------

  # 4. Install Dependencies (Frontend)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'apps/web'

  # 5. Build Production Assets
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}'
      - 'VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}'
      - 'VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}'
      - 'VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}'
    dir: 'apps/web'

  # 6. Deploy to Firebase Hosting
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--only', 'hosting']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/metodo-activa-brain/server:latest'

# Note: You must add the Substitution Variables starting with _VITE_... in Cloud Build Trigger settings.
